### ISSUE TITLE
Añadir más opciones en la pestaña de Mi Perfil

### ISSUE THREAD

**Issue by unaipme** [Runnstein/RunnsteinFrontEnd#17]
Está muy vacía. ¿Qué tal que una de las cuadrículas sea para modificar la dirección, y otra para el teléfono?

**Comment by urkopineda** [comment]
Hay que pensar en el tiempo, por eso no he añadido nada más a 'ProfileUI'.

**Comment by urkopineda** [comment]
En la versión v0.20.9 ya esta la UI modificada para cargar los datos. Además, al inicio ya hacemos un 'SELECT' para recoger todos los datos de 'Dirección' y 'Teléfono' en 'Configuration'.

Queda cargar los datos en los 'JTextField' de 'ProfileUI' con los datos de 'Configuration' y, cuando se puse 'Guardar', que haga 'INSERT' o 'UPDATE' de los datos.

**Comment by urkopineda** [comment]
Solucionado en v0.21.3.
