### ISSUE TITLE
Pasar todos los Strings al archivo XML.

### ISSUE THREAD

**Issue by urkopineda** [Runnstein/RunnsteinFrontEnd#20]
Pasarlos al XML y actualizar UI para utilizar la clase 'Strings' para cargar los Strings.

**Comment by unaipme** [comment]
Me asigno yo esto, que no me cuesta nada hacerlo.

**Comment by urkopineda** [comment]
Subidos Strings en la v0.21.6.2, solo falta cambiar las clases con los nuevos Strings. Para mi!

**Comment by urkopineda** [comment]
v0.22.0
