### ISSUE TITLE
Crear datos vacíos al registrarse

### ISSUE THREAD

**Issue by unaipme** [Runnstein/RunnsteinFrontEnd#22]
En mi opinión, cuando se registra una persona, se debería introducir un nuevo dato en las tablas de Direccion y Telefono para que así, en el futuro, cuando se quiera modificar o consultar la dirección, el dato ya existirá (No habrá que hacer Insert) y solo habrá que extraerlo (Select) o modificarlo (Update).

**Comment by urkopineda** [comment]
Es añadir unos datos más a 'SignInUI', para mi!

**Comment by urkopineda** [comment]
Solucionado en v0.21.2.
