### ISSUE TITLE
Añadir pantallas de carga

### ISSUE THREAD

**Issue by urkopineda** [Runnstein/RunnsteinFrontEnd#6]
Habría que añadir pantallas de carga para hacer al usuario más visual la espera de todos los SELECTs que se hacen al hacer log in.

**Comment by unaipme** [comment]
Asígname esto a mí que ya estoy en ello.

**Comment by unaipme** [comment]
Esto está hecho, solo quedaría implementarlo.

Yo, por ejemplo, ya lo he implementado en el Player. Asigno a @urkopineda implementarlo en otras partes, por ejemplo, cuando conecta con la base de datos y tal y cual.

**Comment by urkopineda** [comment]
Finalmente añadidas todas las pantallas donde la carga es bastante pesada en v0.20.7.
